# Generated by Django 5.2.6 on 2025-10-01 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('trancado', 'Trancado')], default='ativo', max_length=10)),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Saldo Credor (Crédito)')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('stage', models.IntegerField(default=1, verbose_name='Estágio')),
                ('anotacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Anotações dos Professores')),
            ],
        ),
        migrations.CreateModel(
            name='AcompanhamentoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_sequencia', models.DateField(verbose_name='Início da Sequência de Faltas')),
                ('numero_de_faltas', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido')], default='pendente', max_length=10)),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo das Faltas e Ações Tomadas')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='cadastros.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('anual', 'Anual'), ('semestral', 'Semestral'), ('flex', 'Mensal Flexível')], max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('parcelas_matricula', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastros.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensalidade', 'Mensalidade'), ('matricula', 'Matrícula'), ('material', 'Material Didático'), ('outro', 'Outro')], default='mensalidade', max_length=15, verbose_name='Tipo de Pagamento')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('parcial', 'Parcialmente Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valor Pago')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='cadastros.aluno')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('last_parag', models.IntegerField(blank=True, null=True, verbose_name='Último Parágrafo')),
                ('last_word', models.CharField(blank=True, max_length=100, null=True, verbose_name='Última Palavra')),
                ('new_dictation', models.IntegerField(blank=True, null=True, verbose_name='Ditado Novo (Nº)')),
                ('old_dictation', models.IntegerField(blank=True, null=True, verbose_name='Ditado Antigo (Nº)')),
                ('new_reading', models.IntegerField(blank=True, null=True, verbose_name='Leitura Nova (Nº)')),
                ('old_reading', models.IntegerField(blank=True, null=True, verbose_name='Leitura Antiga (Nº)')),
                ('lesson_check', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson Check')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('registro_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.registroaula')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matriculado', 'Matriculado'), ('acompanhando', 'Acompanhando'), ('experimental', 'Experimental'), ('trancado', 'Trancado')], default='matriculado', max_length=15)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turma')),
            ],
        ),
    ]
