# Generated by Django 5.2.6 on 2025-10-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_aluno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='saldo_credito',
        ),
    ]
