# Generated by Django 5.2.6 on 2025-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_horarioaula_testestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('novo', 'Novo Contato'), ('contatado', 'Contato Realizado'), ('agendado', 'Aula Experimental Agendada'), ('convertido', 'Convertido em Aluno'), ('perdido', 'Perdido')], default='novo', max_length=15)),
                ('fonte_contato', models.CharField(blank=True, choices=[('indicacao', 'Indicação'), ('instagram', 'Instagram'), ('google', 'Google'), ('fachada', 'Fachada da Escola'), ('outro', 'Outro')], max_length=15, verbose_name='Origem do Contato')),
                ('disponibilidade_horarios', models.TextField(blank=True, verbose_name='Disponibilidade de Horários')),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
