# Generated by Django 5.2.6 on 2025-10-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_tokenatualizacaoaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=15)),
                ('data_agendamento', models.DateTimeField(verbose_name='Data e Hora do Agendamento')),
                ('data_realizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Realização')),
                ('stage_no_momento', models.IntegerField(verbose_name='Stage do Aluno no Momento do Acompanhamento')),
                ('dificuldades', models.TextField(blank=True)),
                ('relacao_lingua', models.TextField(blank=True, verbose_name='Relação com a língua')),
                ('objetivo_estudo', models.TextField(blank=True, verbose_name='Objetivo do estudo')),
                ('correcao_ditados', models.TextField(blank=True, verbose_name='Correção de ditados')),
                ('pontos_fortes', models.TextField(blank=True)),
                ('pontos_melhorar', models.TextField(blank=True, verbose_name='Pontos a serem melhorados')),
                ('estrategia', models.TextField(blank=True, verbose_name='Estratégia')),
                ('comentarios_extras', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos_pedagogicos', to='cadastros.aluno')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_criados', to='cadastros.professor')),
            ],
            options={
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
