# Generated by Django 5.2.6 on 2025-10-09 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_aluno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Prova')),
                ('stage_referencia', models.IntegerField(verbose_name='Stage de Referência')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções Gerais')),
                ('pontos_para_aprovar', models.IntegerField(blank=True, null=True, verbose_name='Pontos para Aprovar')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gabarito de Prova',
                'verbose_name_plural': 'Gabaritos de Provas',
                'ordering': ['stage_referencia', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AlunoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_correcao', 'Aguardando Correção'), ('finalizada', 'Finalizada')], default='aguardando_correcao', max_length=20)),
                ('data_realizacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Realização')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, verbose_name='Observações Gerais do Professor')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='cadastros.aluno')),
                ('corrigido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.professor')),
                ('prova_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.provatemplate', verbose_name='Gabarito da Prova')),
            ],
            options={
                'verbose_name': 'Prova do Aluno',
                'verbose_name_plural': 'Provas dos Alunos',
                'ordering': ['-data_realizacao'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('tipo_questao', models.CharField(choices=[('dictation', 'Dictation'), ('yes_no', 'Yes/No Quiz'), ('multiple_choice', 'Multiple Choice (Escrito)'), ('error_correction', 'Error Correction'), ('oral_multiple_choice', 'Multiple Choice (Oral)'), ('gap_fill', 'Gap Fill')], max_length=30, verbose_name='Tipo da Questão')),
                ('enunciado', models.TextField(verbose_name='Enunciado/Instrução')),
                ('pontos', models.IntegerField(default=1, verbose_name='Pontos')),
                ('dados_questao', models.JSONField(blank=True, help_text='Ex: {"opcoes": {"a": "A", "b": "B"}, "resposta_correta": "b"}', null=True)),
                ('prova_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='cadastros.provatemplate')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['prova_template', 'ordem'],
            },
        ),
    ]
