# Generated by Django 5.2.6 on 2025-10-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_provatemplate_alunoprova_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='provatemplate',
            name='ordem_sessoes',
            field=models.JSONField(default=list, help_text='Lista com a ordem dos tipos de questão. Ex: ["dictation", "yes_no"]', verbose_name='Ordem das Secções'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo_questao',
            field=models.CharField(choices=[('dictation', 'Dictation'), ('yes_no', 'Yes/No Quiz'), ('multiple_choice', 'Multiple Choice (Escrito)'), ('error_correction', 'Error Correction'), ('oral_multiple_choice', 'Multiple Choice (Oral)'), ('gap_fill', 'Gap Fill'), ('dissertativa', 'Escrita / Dissertativa')], max_length=30, verbose_name='Tipo da Questão'),
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True, verbose_name='Resposta em Texto')),
                ('resposta_opcao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Opção Selecionada')),
                ('pontos_obtidos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_professor', models.TextField(blank=True, null=True, verbose_name='Feedback do Professor')),
                ('corrigido', models.BooleanField(default=False)),
                ('aluno_prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cadastros.alunoprova')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.questao')),
            ],
            options={
                'ordering': ['questao__ordem'],
                'unique_together': {('aluno_prova', 'questao')},
            },
        ),
    ]
