# Generated by Django 5.2.6 on 2025-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_provatemplate_ordem_sessoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoprova',
            name='status',
            field=models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_progresso', 'Em Progresso'), ('aguardando_correcao', 'Aguardando Correção'), ('finalizada', 'Finalizada')], default='nao_iniciada', max_length=20),
        ),
    ]
