# Generated by Django 5.2.6 on 2025-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_alunoprova_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provatemplate',
            name='instrucoes_sessoes',
            field=models.JSONField(blank=True, default=dict, help_text='Dicionário com instruções por tipo de questão. Ex: {"yes_no": "Ouça e marque Sim ou Não."}', verbose_name='Instruções das Secções'),
        ),
    ]
