# Generated by Django 5.2.6 on 2025-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_provatemplate_instrucoes_sessoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoprova',
            name='pontuacao_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pontuação Máxima da Prova'),
        ),
    ]
