# Generated by Django 5.2.6 on 2025-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alunoprova_pontuacao_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('matriculado', 'Matriculado'), ('acompanhando', 'Acompanhando'), ('experimental', 'Experimental'), ('trancado', 'Trancado'), ('desistiu', 'Desistiu')], default='matriculado', max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo Contato'), ('contatado', 'Contato Realizado'), ('agendado', 'Aula Experimental Agendada'), ('congelado', 'Congelado'), ('convertido', 'Convertido em Aluno'), ('perdido', 'Perdido')], default='novo', max_length=15),
        ),
    ]
