# Generated by Django 5.2.6 on 2025-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_inscricao_status_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='atividades_recomendadas',
            field=models.TextField(blank=True, null=True, verbose_name='Atividades e Recomendações'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='resposta_corrigida_html',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta Corrigida (HTML)'),
        ),
    ]
