# Generated by Django 5.2.6 on 2025-11-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_acompanhamentopedagogico_atividades_recomendadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaula',
            name='new_dictation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ditado Novo'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='new_reading',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Nova'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='old_dictation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ditado Antigo'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='old_reading',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Antiga'),
        ),
    ]
