# Generated by Django 5.2.6 on 2025-10-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_acompanhamentopedagogico_atividades_recomendadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaula',
            name='new_dictation',
            field=models.CharField(blank=True, null=True, verbose_name='Ditado Novo (Nº)'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='new_reading',
            field=models.CharField(blank=True, null=True, verbose_name='Leitura Nova (Nº)'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='old_dictation',
            field=models.CharField(blank=True, null=True, verbose_name='Ditado Antigo (Nº)'),
        ),
        migrations.AlterField(
            model_name='registroaula',
            name='old_reading',
            field=models.CharField(blank=True, null=True, verbose_name='Leitura Antiga (Nº)'),
        ),
    ]
