# Generated by Django 5.2.6 on 2025-12-03 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_registroaula_new_dictation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='professores_fotos/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='funcao',
            field=models.CharField(choices=[('teacher', 'Teacher (Professor)'), ('administrativo', 'Administrativo/Recepção'), ('pedagogico', 'Coordenação Pedagógica')], default='teacher', max_length=20),
        ),
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('email_confirmado', models.EmailField(max_length=254, verbose_name='Para começarmos, qual o seu melhor e-mail para contato?')),
                ('telefone_atualizado', models.CharField(max_length=20, verbose_name='E o seu número de WhatsApp atualizado?')),
                ('stage_atual_informado', models.IntegerField(verbose_name='Em qual Stage você acredita que está hoje?')),
                ('nps_score', models.IntegerField(help_text='0 = Nada Provável, 10 = Extremamente Provável', verbose_name='De 0 a 10, quanto você recomendaria a MMS para um amigo?')),
                ('segue_instagram', models.BooleanField(default=False, verbose_name='Você já segue a gente no Instagram (@mmsinstitute)?')),
                ('motivo_nao_seguir', models.TextField(blank=True, null=True, verbose_name='Ah, que pena! Conta pra gente, por que ainda não segue?')),
                ('conteudo_desejado', models.TextField(blank=True, null=True, verbose_name='O que você gostaria de ver mais no nosso Instagram?')),
                ('ajuda_extra_classe', models.BooleanField(default=False, verbose_name='A equipe da MMS já te ajudou com algo fora da sala de aula? (Ex: TOEFL, Intercâmbio, Currículo)')),
                ('detalhe_ajuda', models.TextField(blank=True, null=True, verbose_name='Que legal! Conta pra gente como foi essa ajuda:')),
                ('comentarios_gerais', models.TextField(blank=True, null=True, verbose_name='Este espaço é todo seu! Queremos ouvir seus elogios, críticas ou sugestões de coração:')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas_satisfacao', to='cadastros.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfacao_aulas', models.IntegerField(verbose_name='De modo geral, o quão satisfeito você está com as aulas deste teacher?')),
                ('incentivo_teacher', models.IntegerField(verbose_name='O quanto você sente que este teacher te mantém motivado e incentivado?')),
                ('seguranca_conforto', models.IntegerField(verbose_name='Você se sente seguro e confortável para participar e tirar dúvidas nas aulas dele(a)?')),
                ('esforco_conteudo', models.IntegerField(verbose_name='O quanto você percebe que o teacher se esforça para explicar o conteúdo de forma clara?')),
                ('elogio', models.TextField(blank=True, verbose_name="Mande um 'Que Bom!' (Elogio)")),
                ('sugestao', models.TextField(blank=True, verbose_name="Deixe um 'Que Pena' (Sugestão de melhoria)")),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.professor')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_professores', to='cadastros.pesquisasatisfacao')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participou_acompanhamento', models.BooleanField(verbose_name='Você já fez algum Acompanhamento Pedagógico com a teacher?')),
                ('satisfacao_atendimento', models.IntegerField(blank=True, null=True, verbose_name='Se sim, quão satisfeito você ficou com esse atendimento?')),
                ('atividades_interessantes', models.TextField(blank=True, verbose_name='Que atividades você acredita que contribuíram para o seu aprendizado no acompanhamento?')),
                ('elogio', models.TextField(blank=True, verbose_name='Deixe seu elogio para o pedagógico:')),
                ('sugestao', models.TextField(blank=True, verbose_name='Sua sugestão de melhoria para o pedagógico:')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.professor')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_pedagogico', to='cadastros.pesquisasatisfacao')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educacao_prestatividade', models.IntegerField(verbose_name='O quão educado e prestativo foi o atendimento quando você precisou?')),
                ('avaliacao_geral', models.IntegerField(verbose_name='Considerando suas últimas experiências, como você avalia o atendimento?')),
                ('nivel_satisfacao', models.IntegerField(verbose_name='Qual seu nível geral de satisfação com a nossa recepção/administração?')),
                ('destaques', models.JSONField(default=list, verbose_name='O que se destaca no atendimento?')),
                ('elogio', models.TextField(blank=True, verbose_name='Deixe seu elogio para o atendimento:')),
                ('sugestao', models.TextField(blank=True, verbose_name='Sua sugestão de melhoria:')),
                ('membro_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.professor')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_adm', to='cadastros.pesquisasatisfacao')),
            ],
        ),
    ]
