# Generated by Django 5.2.6 on 2025-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_professor_ativo_professor_foto_professor_funcao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='funcao',
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='area_atuacao',
            field=models.CharField(blank=True, help_text='Ex: Psicologia, TI, Engenharia, Vendas...', max_length=100, null=True, verbose_name='Área de Atuação'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='bairro_residencia',
            field=models.CharField(blank=True, help_text='Para mapeamento geográfico', max_length=100, null=True, verbose_name='Bairro onde mora'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='cargo_atual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Ocupação Atual'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='como_conheceu',
            field=models.CharField(blank=True, choices=[('indicacao', 'Indicação de Amigo/Familiar'), ('instagram', 'Instagram / Redes Sociais'), ('google', 'Google / Pesquisa'), ('fachada', 'Passei na frente / Fachada'), ('evento', 'Eventos / Palestras')], max_length=20, null=True, verbose_name='Como conheceu a MMS?'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('medio', 'Ensino Médio'), ('superior_cursando', 'Ensino Superior (Cursando)'), ('superior_completo', 'Ensino Superior (Completo)'), ('pos_graduacao', 'Pós-Graduação / MBA / Mestrado / Doutorado')], max_length=20, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('12-17', '12 a 17 anos (Teen)'), ('18-24', '18 a 24 anos (Jovem Adulto)'), ('25-34', '25 a 34 anos (Adulto)'), ('35-44', '35 a 44 anos (Adulto)'), ('45+', '45 anos ou mais')], max_length=10, null=True, verbose_name='Faixa Etária'),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='objetivo_ingles',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Maior objetivo com o inglês'),
        ),
        migrations.AddField(
            model_name='professor',
            name='eh_administrativo',
            field=models.BooleanField(default=False, verbose_name='É Administrativo?'),
        ),
        migrations.AddField(
            model_name='professor',
            name='eh_pedagogico',
            field=models.BooleanField(default=False, verbose_name='É Pedagógico?'),
        ),
        migrations.AddField(
            model_name='professor',
            name='eh_teacher',
            field=models.BooleanField(default=False, verbose_name='É Teacher?'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='ajuda_extra_classe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='comentarios_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários Gerais'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='conteudo_desejado',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo desejado'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='detalhe_ajuda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='email_confirmado',
            field=models.EmailField(max_length=254, verbose_name='E-mail confirmado'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='motivo_nao_seguir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='nps_score',
            field=models.IntegerField(verbose_name='NPS (0-10)'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='segue_instagram',
            field=models.BooleanField(default=False, verbose_name='Segue Instagram?'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='stage_atual_informado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='telefone_atualizado',
            field=models.CharField(max_length=20, verbose_name='Telefone atualizado'),
        ),
    ]
