# Generated by Django 5.2.6 on 2025-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_remove_professor_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='creditos_aulas',
            field=models.IntegerField(default=0, verbose_name='Créditos (Mensalidades)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('trancado', 'Trancado (Gerando Créditos)'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='como_conheceu',
            field=models.CharField(blank=True, choices=[('indicacao', 'Indicação de Amigo/Familiar'), ('instagram', 'Instagram / Redes Sociais'), ('google', 'Google / Pesquisa'), ('evento', 'Eventos / Palestras'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Como conheceu a MMS?'),
        ),
    ]
