# Generated by Django 5.2.6 on 2025-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_aluno_creditos_aulas_contrato_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo Contato'), ('contatado', 'Em contato'), ('interessado', 'Interessado'), ('teste_nivel', 'Teste de Nível'), ('agendado', 'Aula Experimental Agendada'), ('congelado', 'Follow-up'), ('negociacao', 'Em Negociação'), ('convertido', 'Convertido em Aluno'), ('perdido', 'Perdido')], default='novo', max_length=15),
        ),
    ]
