# Generated by Django 5.2.6 on 2025-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoadministrativo',
            name='avaliacao_geral',
            field=models.IntegerField(blank=True, null=True, verbose_name='Considerando suas últimas experiências, como você avalia o atendimento?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoadministrativo',
            name='educacao_prestatividade',
            field=models.IntegerField(blank=True, null=True, verbose_name='O quão educado e prestativo foi o atendimento quando você precisou?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoadministrativo',
            name='nivel_satisfacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qual seu nível geral de satisfação com a nossa recepção/administração?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessor',
            name='esforco_conteudo',
            field=models.IntegerField(blank=True, null=True, verbose_name='O quanto você percebe que o teacher se esforça para explicar o conteúdo de forma clara?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessor',
            name='incentivo_teacher',
            field=models.IntegerField(blank=True, null=True, verbose_name='O quanto você sente que este teacher te mantém motivado e incentivado?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessor',
            name='satisfacao_aulas',
            field=models.IntegerField(blank=True, null=True, verbose_name='De modo geral, o quão satisfeito você está com as aulas deste teacher?'),
        ),
        migrations.AlterField(
            model_name='avaliacaoprofessor',
            name='seguranca_conforto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Você se sente seguro e confortável para participar e tirar dúvidas nas aulas dele(a)?'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='telefone_atualizado',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefone atualizado'),
        ),
    ]
