# Generated by Django 5.2.6 on 2026-04-17 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_avaliacaoadministrativo_avaliacao_geral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='motivo_descarte',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Descarte'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage_interesse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stage de Interesse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='token_disponibilidade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fonte_contato',
            field=models.CharField(blank=True, choices=[('indicacao', 'Indicação'), ('instagram', 'Instagram'), ('google', 'Google'), ('fachada', 'Fachada da Escola'), ('whatsapp', 'WhatsApp'), ('outro', 'Outro')], max_length=15, verbose_name='Origem do Contato'),
        ),
        migrations.CreateModel(
            name='HorarioDisponivelLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='cadastros.lead')),
            ],
            options={
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
    ]
