# Generated by Django 5.2.6 on 2026-04-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_lead_motivo_descarte_lead_stage_interesse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Template')),
                ('conteudo', models.TextField(help_text='Use {{nome}} para injetar o nome do lead.', verbose_name='Conteúdo (Variáveis: {{nome}})')),
                ('categoria', models.CharField(choices=[('triagem', 'Triagem'), ('follow_up', 'Follow Up'), ('objecao', 'Quebra de Objeção'), ('aviso', 'Aviso / Lembrete'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('entrada', 'Recebida (Cliente -> Escola)'), ('saida', 'Enviada (Escola -> Cliente)')], max_length=10, verbose_name='Direção da Mensagem')),
                ('conteudo_texto', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('wamid', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Message ID')),
                ('status', models.CharField(blank=True, choices=[('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('falha', 'Falha')], max_length=15, null=True, verbose_name='Status de Entrega')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_whatsapp', to='cadastros.lead')),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
