# Generated by Django 5.2.6 on 2026-04-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_templatemensagem_mensagemwhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateTimeField(auto_now_add=True)),
                ('tipo_contato', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('ligacao', 'Ligação'), ('email', 'E-mail'), ('presencial', 'Presencial')], default='whatsapp', max_length=15, verbose_name='Tipo de Contato')),
                ('anotacoes', models.TextField(verbose_name='Anotações / Resumo da Conversa')),
                ('lead_respondeu', models.BooleanField(default=False, verbose_name='O lead respondeu?')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='cadastros.lead')),
            ],
            options={
                'ordering': ['-data_contato'],
            },
        ),
        migrations.RemoveField(
            model_name='mensagemwhatsapp',
            name='lead',
        ),
        migrations.DeleteModel(
            name='TemplateMensagem',
        ),
        migrations.DeleteModel(
            name='MensagemWhatsApp',
        ),
    ]
