# Generated by Django 5.2.6 on 2026-04-23 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_followup_remove_mensagemwhatsapp_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='observacoes_trancamento',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações de Trancamento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='token_disponibilidade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='HorarioDisponivelAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='cadastros.aluno')),
            ],
        ),
    ]
