# Generated by Django 5.2.6 on 2026-04-23 13:34

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Aluno = apps.get_model('cadastros', 'Aluno')
    for row in Aluno.objects.all():
        row.token_disponibilidade = uuid.uuid4()
        row.save(update_fields=['token_disponibilidade'])

class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_aluno_observacoes_trancamento_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aluno',
            name='token_disponibilidade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
