# Generated by Django 5.2.6 on 2026-04-23 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_aluno_observacoes_trancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='token_disponibilidade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
