# Generated by Django 5.2.6 on 2026-05-06 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_alter_aluno_token_disponibilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentopedagogico',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='acompanhamentopedagogico',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='acompanhamentopedagogico',
            name='data_realizacao',
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='grammar',
            field=models.TextField(blank=True, verbose_name='Grammar'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='listening',
            field=models.TextField(blank=True, verbose_name='Listening'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='reading',
            field=models.TextField(blank=True, verbose_name='Reading'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='speaking',
            field=models.TextField(blank=True, verbose_name='Speaking'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='tipo',
            field=models.CharField(choices=[('primeiro', 'Primeiro Acompanhamento'), ('seguinte', 'Acompanhamento Seguinte')], default='primeiro', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='acompanhamentopedagogico',
            name='vocabulary',
            field=models.TextField(blank=True, verbose_name='Vocabulary'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogico',
            name='comentarios_extras',
            field=models.TextField(blank=True, verbose_name='Comentários Extras'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogico',
            name='dificuldades',
            field=models.TextField(blank=True, verbose_name='Issues (Dificuldades)'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogico',
            name='pontos_fortes',
            field=models.TextField(blank=True, verbose_name='Pontos Fortes'),
        ),
        migrations.AlterField(
            model_name='acompanhamentopedagogico',
            name='pontos_melhorar',
            field=models.TextField(blank=True, verbose_name='Improvements (Pontos a Melhorar)'),
        ),
    ]
