# Generated by Django 5.2.6 on 2026-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_alter_acompanhamentopedagogico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição / Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('categoria', models.CharField(choices=[('administrativo', 'Administrativo (Água, Luz, Internet, etc.)'), ('folha_pagamento', 'Folha de Pagamento / Professores'), ('marketing', 'Marketing e Vendas'), ('infraestrutura', 'Infraestrutura e Manutenção'), ('impostos', 'Impostos e Taxas'), ('outro', 'Outro')], default='administrativo', max_length=20, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
