# Generated by Django 5.2.6 on 2026-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
